"""create Dock and InboundShipment table

Revision ID: 6457128aa452
Revises: 
Create Date: 2026-06-28 15:38:39.467464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6457128aa452'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('docks',
    sa.Column('dock_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('dock_id')
    )
    op.create_table('inbound_shipments',
    sa.Column('inbound_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('arrival_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dock_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dock_id'], ['docks.dock_id'], ),
    sa.PrimaryKeyConstraint('inbound_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inbound_shipments')
    op.drop_table('docks')
    # ### end Alembic commands ###
